version: '3.9'

services:
  # nginx reverse proxy to connect,
  # forward requests to apps on the host
  # base service, supposed to be extended
  proxy-to-host:
    image: nginx:alpine
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../nginx/nginx-http.conf.template:/tmp/nginx-http.conf.template:ro
      - ../nginx/nginx-grpc.conf.template:/tmp/nginx-grpc.conf.template:ro
      - ../scripts/start_nginx.sh:/bin/start_nginx.sh:ro
    expose:
      - 8080
    command: /bin/start_nginx.sh
